config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  devise_for :users

  root 'players#index'
  resources :players

  resources :games

  resources :studies

  resources :pgns

  mount Sidekiq::Web, at: '/sidekiq'
end

app/models/game.rb
class Game < ActiveRecord::Base
  validates :notation, presence: true
  has_and_belongs_to_many :players
  mount_uploader :pgn, PgnUploader
end

app/models/pgn.rb
class Pgn < ActiveRecord::Base
  validates :pgn, presence: true
  mount_uploader :pgn, PgnUploader

end

app/models/player.rb
class Player < ActiveRecord::Base
  validates :name, presence: true
  validates :rating, presence: true

  has_and_belongs_to_many :games
end

app/models/study.rb
class Study < ActiveRecord::Base
  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  respond_to :js, :json, :html

  def new
    @players = Player.all
    @game = Game.new
  end

  def create
    @players = Player.all
    @game = Game.new(game_params)
    @game.pgn = game_params[:file]
    if params[:player_ids]
      players = Player.find(params[:player_ids])
      players.each do |player|
        @game.players.push(player)
      end
    else
      @game = Game.new({notation: ""})
    end
    if @game.save
      redirect_to game_path(@game)
    else
      flash[:alert] = "Games must have a PGN and a player selected."
      redirect_to new_game_path
    end
  end


  def show
    @game = Game.find(params[:id])
  end

  def edit
    @game = Game.find(params[:id])
    @players = Player.all
  end

  def update
    respond_with do |format|
      format.html do
        @game = Game.find(params[:id])
        unless @game.update(game_params)
          flash[:alert] = "PGN can't be blank"
          puts 'game update section'
          redirect_to game_path(@game)
        end
        format.js do
          @game = Game.find(params[:gameNum])
          @game.notation = params[:gameNotation]
          puts 'pgn format response'
          render nothing: true
        end
      end
    end
  end
    #
    # respond_to do |format|
    #   format.js do
    #     # binding.pry
    #     @game = Game.find(params[:gameNum])
    #     @game.notation = params[:gameNotation]
    #     puts 'pgn format response'
    #     render nothing: true
    #   end
    # end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to players_path
  end

private
  def game_params
    params.permit(:notation, :player_id, :pgn)
  end
end

app/controllers/pgns_controller.rb
# This is kind of awkward. but for now, separating adding game by PGN parser, and games played or put in manually is easiest.
class PgnsController < ApplicationController


private
  def pgn_params
    params.require(:pgn).permit(:pgn)
  end

public
  def new
    @pgn = Pgn.new
  end

  def create
    @pgn = Pgn.new(pgn_params)
    if @pgn.save
    # binding.pry
      PgnsWorker.perform_async(@pgn.id)
      redirect_to pgn_path(@pgn)
    else
      flash[:alert] = "Something Went wrong."
      redirect_to new_pgn_path
    end
  end


  def show
    @pgn = Pgn.find(params[:id])
  end

  def edit
    @game = Game.find(params[:id])
    @players = Player.all
  end

  def update
    @game = Game.find(params[:id])
    if @game.update(game_params)
      redirect_to game_path(@game)
    else
      flash[:alert] = "PGN can't be blank"
      redirect_to game_path(@game)
    end
  end

  def destroy
    game = Game.find(params[:id])
    game.destroy
    redirect_to players_path
  end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!
  respond_to :js, :json, :html

  private
    def player_params
      params.require(:player).permit(:name, :rating)
    end

  public
  def index
    # refactor this into something respectable
    @user = current_user
    @players = Player.all
    pgn = params[:game_pgn]
    moves = params[:moves]
    turn = params[:turn]
    win_cons = ['1-0','0-1','½–½']
    white_win = "1-0"
    black_win = "0-1"
    draw = "1/2-1/2"
    if moves
      @games = Game.where("notation LIKE ?", "#{pgn}%")
      @moves_a = []
      @white_wins = []
      @black_wins = []
      @draws = []
      # adds space and move number to pgn to allow for DB searching.
      if turn == 'w'
        number = pgn.scan(/\d\./)
        convert = number.last.to_i
        addToGame = convert + 1
        newStringNum = addToGame.to_s
        pgn.concat(" " + newStringNum + ".")
      end
      moves.each do |move|
          number = @games.where("notation LIKE ?", "#{pgn} #{move}%")
          @moves_a << number.length
          white_wins = @games.where("notation LIKE ? AND notation LIKE ?", "#{pgn} #{move}%", "%#{white_win}%")
          black_wins = @games.where("notation LIKE ? AND notation LIKE ?", "#{pgn} #{move}%", "%#{black_win}%")
          draws      = @games.where("notation LIKE ? AND notation LIKE ?", "#{pgn} #{move}%", "%#{draw}%")
          @white_wins << white_wins.length
          @black_wins << black_wins.length
          @draws << draws.length
      end
      # binding.pry
      respond_with do |format|
        format.html

        format.json do
          render json: {
            moves: moves,
            white_wins: @white_wins,
            black_wins: @black_wins,
            draws: @draws,
            next_move: @moves_a
          }.to_json
        end
      end
    end
  end

  def new
    @player = Player.new
    @players = Player.all
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to player_path(@player)
    else
      flash[:alert] = "All Fields must be filled in."
      render :index
    end
  end

  def show
    @player = Player.find(params[:id])
    @games = @player.games.all
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])
    if @player.update(player_params)
      redirect_to player_path(@player)
    else
      render :edit
    end
  end

  def destroy
    player = Player.find(params[:id])
    player.destroy
    redirect_to players_path
  end

end

app/controllers/studies_controller.rb
class StudiesController < ApplicationController

  def show
    @study = Study.find(params[:id])
    name = @study.name
    @study_info = Wikipedia.find(name)
    @study_page = @study_info.text
    # == on wiki is header, === subheader.
    @study_page.gsub!(/([===])/, "<br>")
  end

  def new
    @study = Study.new
  end

  def create
    @study = Study.create(study_params)
    redirect_to study_path(@study)
  end

private
  def study_params
    params.require(:study).permit(:name)
  end

end

app/controllers/study_controller.rb
class StudyController < ApplicationController

  def show

  end

  def index
# == on wiki is header, === subheader.
    @response = Wikipedia.find('Pawn_structure')
    # @images = @response.image_urls
    # @images.each do |image|
    @content = @response.text
    # count = @content.scan(/(?=#{"===".downcase()})/).count
    @content.gsub!(/([===])/, "<br>")
    # binding.pry

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_for @game, :html => {multipart: true} do |f| %>
  <div class="form-group">
    <%= f.label :notation %>
    <%= f.text_field :notation, class: "form-control", id: "game_notation_form" %>
  </div>
  <div class="form-group">
    <%= f.file_field :pgn %>
  </div>

  <% @players.each do |player| %>
    <%= label_tag player.name %>
    <%= check_box_tag "player_ids[]", player.id %>
  <% end %>

<br>
  <%= f.submit "Add" %>
<% end %>

app/views/games/edit.html.erb
<h3>Edit this game :</h3>
<%= render 'form' %>

app/views/games/new.html.erb
<% content_for(:new_game_active, "active") %>
<h3>New Game Notation:</h3>

<%= render 'form' %>

app/views/games/new.js.erb
var pgn = game.pgn();
$('#game_save_form').append('<%= j render("form") %>')
$('#game_notation_form').val(pgn)

app/views/games/show.html.erb
<div id="ind_game_pgn"><%= @game.notation %></div>
<div id="show_game_board"></div>
<div class="well well-sm">
  <input type="button" id="startBtn" value="Start">
  <input type="button" id="clearBtn" value="Clear">
  <input type="button" id="undoBtn" value="Undo">
  <input type="button" id="moveBtn" value="Move">
</div>

<br>

<h5><%= link_to 'Edit this game', edit_game_path(@game) %></h5>
<h5><%= link_to 'Delete this game', game_path(@game), data: {confirm: "Are You Sure?", method: "delete"} %></h5>

<%= javascript_include_tag '/assets/javascripts/chess', "data-turbolinks-track" => true %>
<%= javascript_include_tag '/assets/javascripts/chessboard', "data-turbolinks-track" => true %>
<%= javascript_include_tag '/assets/javascripts/chessStudyBoard', "data-turbolinks-track" => true %>
<%= javascript_include_tag '/assets/javascripts/addGame', "data-turbolinks-track" => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chess</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div id="bunker">

    <div id='sidebar'>
        <% if user_signed_in? %>
        <ul>
          <li class='<%= yield(:index_active)%>'><%= link_to "Chess", root_path %></a></li>
          <li class='<%= yield(:new_game_active)%>' ><%= link_to 'Add a new game', new_game_path %></li>
          <li class='<%= yield(:new_player_active)%>' ><%= link_to 'Add a new Player', new_player_path %></li>
          <li class='<%= yield(:new_study_active)%>' ><%= link_to 'Study', new_study_path %></li>
          <li class='<%= yield(:edit_profile_active)%>' ><%= link_to 'Edit Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: 'delete' %></li>
        </ul>
         <% else %>
          <ul>
            <li class='<%= yield(:new_player_active)%>' ><%= link_to 'Login', new_user_session_path %></li>
            <li class='<%= yield(:new_player_active)%>' ><%= link_to 'Sign Up', new_user_registration_path %></li>
          </ul>
         <% end %>
    </div>
    <%= yield %>
   <!-- </div> -->
    </div>
</body>
</html>

app/views/pgns/_form.html.erb
<%= form_for @pgn do |f| %>
  <div class="form-group">
    <%= f.file_field :pgn %>
  </div>
  <%= f.submit "Add" %>
<% end %>

app/views/pgns/new.html.erb
<% content_for(:new_pgn_active, "active") %>
PGNS!
<%= render 'form' %>

app/views/pgns/show.html.erb
PGN SHOW PAGE

app/views/players/_form.html.erb
<%= form_for @player do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, class: "form-control" %>
  </div>

  <%= f.submit "Add" %>
<% end %>

app/views/players/edit.html.erb
<h3>Edit this player:</h3>
<%= render 'form' %>

app/views/players/edit.js.erb
#("#edit_player_info").hide().after('<%= j render("form") %>');

app/views/players/index.html.erb
<% content_for(:index_active, "active") %>
<% if user_signed_in? %>
  <div id="board"></div>
  <div id="media-hidden">
    <div class="well well-sm">
    <input type="button" id="startBtn" value="Start">
    <input type="button" id="clearBtn" value="Clear">
    <input type="button" id="undoBtn" value="Undo">
    <p>Engine Status: <span id="engineStatus"></span></p>
    <p>Status: <span id="status"></span></p>
    <p>FEN: <span id="fen"></span></p>
    <p>PGN: <span id="pgn"></span></p>
    <%= link_to "Save Game", new_game_path, class: "btn btn-default", id: "save_game_board", remote: true %>
    <div id="game_save_form"></div>
    </div>
    <br><br>
    <div id="db_display"></div>
      <div class="well well-sm">
        <h2>Game Database</h2>
        <div class="table-responsive">
          <table class="table-index table-striped">
            <thead>
              <tr>
                <th>Moves</th>
                <th> # of Games</th>
              </tr>
            </thead>
            <tbody id="moves_display">
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
<%= stylesheet_link_tag "home", media: "all", "data-turbolinks-track" => true %>
<%= javascript_include_tag '/assets/stockfish/src/stockfish', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/assets/javascripts/chess', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/assets/javascripts/chessboard', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/assets/javascripts/chessCreate', 'data-turbolinks-track' => true %>
<%= javascript_include_tag '/assets/javascripts/chessEngine', 'data-turbolinks-track' => true %>

app/views/players/new.html.erb
<% content_for(:new_player_active, "active") %>
<h3>Add a new Player</h3>
<%= render 'form' %>

<div id="players-list">
<% @players.each do |player| %>
  <%= link_to player.name, player_path(player) %> <br>
<% end %>

app/views/players/show.html.erb
<h2>Page for <%= @player.name %></h2>
<h4>rating: <%= @player.rating %></h4>


<h5><%= link_to 'Edit this player', edit_player_path(@player), id: "edit_player_info", remote: true %></h5>
<h5><%= link_to 'Delete this player', player_path(@player), data: {confirm: "Are You Sure?", method: "delete"} %></h5>

<br>
<%= link_to 'Add a new game', new_game_path, id: "new_game_link", remote: true %>

<div id="show_game_link">

</div>
<br>
<br>

<% @player.games.each do |game| %>
  <%= link_to game.notation, game_path(game) %>
<% end %>

app/views/studies/_form.html.erb
<%= form_for @study do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <%= f.submit "Search" %>
<% end %>

app/views/studies/new.html.erb
<% content_for(:new_study_active, "active") %>
Research a new Chess Topic
<%= render 'form' %>

app/views/studies/show.html.erb
WELCOME TO THE STUDY PAGE!
<br>
<br>

<p>

<%= @study_page.html_safe %>

</p>